# See https://github.com/crate-ci/typos/blob/master/docs/reference.md to configure typos

[default]
locale = "en"

[default.extend-words]
Hashi = "Hashi" 
Sur = "Sur" 
aks = "aks" 
captable = "captable" # for captan.rb
debugg = "debugg" 
mosquitto = "mosquitto" # for mqtt-cli.rb
ratatui = "ratatui" 
sherif = "sherif" # for sherif.rb
sur = "sur" # for big sur
yor = "yor" 

[files]
extend-exclude = [
  "Formula/h/holo-cli.rb", # for `index 4ba84b7..9d404c0`
  "Formula/m/mitex.rb", # for `main.typ`
  "Formula/r/readmeai.rb", # upstream pr ref, https://github.com/eli64s/readme-ai/pull/158
  "Formula/g/graphjin.rb", # ignore patch
  "patches/flexiblas/3.4.5.patch",
  "patches/fjira/1.4.4.patch",
]

[type.ruby.extend-words]
fo = "fo" # for resinator.rb
